// apps/chain-rice/frontend/src/base/Media.tsx
import React from 'react';

export interface MediaInterface {
  tag?:
    | 'img'
    | 'video'
    | 'audio'
    | 'canvas'
    | 'svg'
    | 'picture'
    | 'source'
    | 'track'
    | 'iframe'
    | 'embed'
    | 'object';
  src?: string;
  alt?: string;
  controls?: boolean;
  autoPlay?: boolean;
  loop?: boolean;
  style?: {
    className?: string;
    width?: string | number;
    height?: string | number;
    initial?: {
      opacity: number;
      x?: number;
      y?: number;
    };
    animate?: {
      opacity: number;
      x?: number;
      y?: number;
    };
    exit?: {
      opacity: number;
      x?: number;
      y?: number;
    };
    transition?: {
      duration: number;
    };
  };
  children?: React.ReactNode;
}

export const Media: React.FC<MediaInterface> = ({
  tag = 'img',
  src,
  alt,
  controls,
  autoPlay,
  loop,
  style,
  children,
  ...props
}) => {
  const getTagClasses = (tag: string) => {
    switch (tag) {
      case 'img':
        return 'max-w-full h-auto rounded-lg shadow-sm border border-gray-200 object-cover';
      case 'video':
        return 'max-w-full h-auto rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'audio':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'canvas':
        return 'max-w-full h-auto rounded-lg shadow-sm border border-gray-200 bg-white';
      case 'svg':
        return 'max-w-full h-auto text-gray-600';
      case 'picture':
        return 'block max-w-full h-auto';
      case 'source':
        return '';
      case 'track':
        return '';
      case 'iframe':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'embed':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'object':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      default:
        return 'max-w-full h-auto';
    }
  };

  const baseClasses = getTagClasses(tag);
  const mediaClasses = `${baseClasses} ${style?.className || ''}`;

  const Component = tag as React.ElementType;

  if (tag === 'img') {
    return (
      <img
        src={src}
        alt={alt}
        className={mediaClasses}
        width={style?.width}
        height={style?.height}
        {...props}
      />
    );
  }

  if (tag === 'video') {
    return (
      <video
        src={src}
        controls={controls}
        autoPlay={autoPlay}
        loop={loop}
        className={mediaClasses}
        width={style?.width}
        height={style?.height}
        {...props}
      >
        {children}
      </video>
    );
  }

  if (tag === 'audio') {
    return (
      <audio
        src={src}
        controls={controls}
        autoPlay={autoPlay}
        loop={loop}
        className={mediaClasses}
        {...props}
      >
        {children}
      </audio>
    );
  }

  if (tag === 'iframe') {
    return (
      <iframe
        src={src}
        className={mediaClasses}
        width={style?.width}
        height={style?.height}
        frameBorder='0'
        allowFullScreen
        {...props}
      >
        {children}
      </iframe>
    );
  }

  if (tag === 'svg') {
    return (
      <svg
        className={mediaClasses}
        width={style?.width}
        height={style?.height}
        {...props}
      >
        {children}
      </svg>
    );
  }

  return (
    <Component
      src={src}
      className={mediaClasses}
      width={style?.width}
      height={style?.height}
      {...props}
    >
      {children}
    </Component>
  );
};

// stacks/frontend/typescript/angular/base/media.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

type Tag =
  | 'img'
  | 'video'
  | 'audio'
  | 'canvas'
  | 'svg'
  | 'picture'
  | 'source'
  | 'track'
  | 'iframe'
  | 'embed'
  | 'object';

@Component({
  selector: 'ui-media',
  standalone: true,
  imports: [CommonModule],
  template: `
    <ng-container [ngSwitch]="tag">
      <img *ngSwitchCase="'img'" [src]="src" [alt]="alt" [class]="computedClasses" [width]="width" [height]="height">
      <video *ngSwitchCase="'video'" [src]="src" [controls]="controls" [autoplay]="autoPlay" [loop]="loop" [class]="computedClasses" [width]="width" [height]="height">
        <ng-content></ng-content>
      </video>
      <audio *ngSwitchCase="'audio'" [src]="src" [controls]="controls" [autoplay]="autoPlay" [loop]="loop" [class]="computedClasses">
        <ng-content></ng-content>
      </audio>
      <canvas *ngSwitchCase="'canvas'" [class]="computedClasses" [width]="width" [height]="height">
        <ng-content></ng-content>
      </canvas>
      <svg *ngSwitchCase="'svg'" [class]="computedClasses" [width]="width" [height]="height">
        <ng-content></ng-content>
      </svg>
      <picture *ngSwitchCase="'picture'" [class]="computedClasses">
        <ng-content></ng-content>
      </picture>
      <iframe *ngSwitchCase="'iframe'" [src]="src" [class]="computedClasses" [width]="width" [height]="height" frameborder="0" allowfullscreen>
        <ng-content></ng-content>
      </iframe>
      <embed *ngSwitchCase="'embed'" [src]="src" [class]="computedClasses" [width]="width" [height]="height">
        <ng-content></ng-content>
      </embed>
      <object *ngSwitchCase="'object'" [data]="src" [class]="computedClasses" [width]="width" [height]="height">
        <ng-content></ng-content>
      </object>
    </ng-container>
  `,
})
export class MediaComponent {
  @Input() tag: Tag = 'img';
  @Input() src?: string;
  @Input() alt?: string;
  @Input() controls = false;
  @Input() autoPlay = false;
  @Input() loop = false;
  @Input() styleClass = '';
  @Input() width?: string | number;
  @Input() height?: string | number;

  get computedClasses(): string {
    const base = this.getTagClasses(this.tag);
    return `${base} ${this.styleClass}`.trim();
  }

  private getTagClasses(tag: Tag): string {
    switch (tag) {
      case 'img':
        return 'max-w-full h-auto rounded-lg shadow-sm border border-gray-200 object-cover';
      case 'video':
        return 'max-w-full h-auto rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'audio':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'canvas':
        return 'max-w-full h-auto rounded-lg shadow-sm border border-gray-200 bg-white';
      case 'svg':
        return 'max-w-full h-auto text-gray-600';
      case 'picture':
        return 'block max-w-full h-auto';
      case 'iframe':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'embed':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      case 'object':
        return 'w-full rounded-lg shadow-sm border border-gray-200 bg-gray-100';
      default:
        return 'max-w-full h-auto';
    }
  }
}
